### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MichaelPachec0** [MichaelPachec0/nodejs-project-night#13]
Probably low priority but a license should be decided upon. Currently the project has a ISC license as the default because of npm init. Need to decide if the license is fine or it should be changed to something like GPL/AGPL or MIT.

**Comment by MichaelPachec0** [comment]
Ill self-assign myself this, since this is out of scope of the project but if the group is interested in OSS licensing then im happy to answer any questions.

**Comment by JoeDravarol** [comment]
I'm not too familar with the other license but it seems like MIT license are very common in open source projects.

**Comment by MichaelPachec0** [comment]
> I'm not too familar with the other license but it seems like MIT license are very common in open source projects.

Yep probably the most common license out there, at least on github. If no one objects to using MIT then id be more than happy to change it.

**Comment by MichaelPachec0** [comment]
Ill take the lack of discussion as sign that people are fine with the change to MIT license. Ill assign this issue to myself and get this fixed both in the repo and in the package.json.

**Comment by JoeDravarol** [comment]
Would be great to also update the README to references the license once it's created in the repo.

**Comment by MichaelPachec0** [comment]
In that case will cover this tomorrow.
