### ISSUE TITLE
Creating the base memory game structure.

### ISSUE THREAD

**Issue by JoeDravarol** [MichaelPachec0/nodejs-project-night#15]
Make the basic HTML structure and some basic styling so that we have a 4/4 grid cells display in the center on the screen. You could try to make it mobile responsive but that isn't neccesary. So ideally it would look like something below without the header.

![image info](https://www.massimogiraldo.com/wp-content/uploads/2020/08/Pokemon-Game-Screenshot.jpg)

**Note**: this was not an agreed layout design it just act as an inspiration/example. I think the group agreed on it being a pokemon card so something along that lines would be great.

**Comment by MichaelPachec0** [comment]
closing since #22 was merged.
