### ISSUE TITLE
UI FIX: Pokemon image is too small.

### ISSUE THREAD

**Issue by JoeDravarol** [MichaelPachec0/nodejs-project-night#44]
The pokemon image that is displayed in the card is too small as shown below:

![UI Issue](https://cdn.discordapp.com/attachments/979643882042187776/981994212708974693/unknown.png)

Propose fix:
**Note**: If you can, you should use the existing CSS class provided and modify the said class to solve this problem. 
- The pokemon image should have the same height and width as the card (Parent); ideally should look like the image shown below: 

![Pokemon card](https://assets.dicebreaker.com/pokemon-tcg-celebrations-cards-mew-charizard-pikachu.png/BROK/thumbnail/1600x900/format/jpg/quality/80/pokemon-tcg-celebrations-cards-mew-charizard-pikachu.png)

**Comment by Mire-web** [comment]
Uploading the solution in a bit

**Comment by JoeDravarol** [comment]
Closing since #52 was merged.
