### ISSUE TITLE
Replace regex with something more descriptive

### ISSUE THREAD

**Issue by MichaelPachec0** [MichaelPachec0/nodejs-project-night#5]
Self explanatory from the title. Code in question is a non-descriptive regex.
https://github.com/MichaelPachec0/nodejs-project-night/blob/25c23338f65ffc950ec4b468a13331199524f017/server.js#L68

While this saves a line of code, its extremely hard to read and will probably create headaches down the road. Ideally break that out into a more descriptive line of code. A possible idea would be to use string split ([mdn link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split)) to split on "." since  file-path is in the form of public/file.ext and use the second entry in the array (the ext part).

If there is a more descriptive way to do this I am all ears. For now I am considering this a bug.

**Comment by Dex-theDev** [comment]
I just tackled a codewars on this very method this morning, i'd like to tackle this one plz

**Comment by MichaelPachec0** [comment]
Awesome, just assigned you for this. Any questions don't hesitate to ask.

**Comment by MichaelPachec0** [comment]
forgot to mention  @Dex-theDev , when you send a pull request in reference to this issue, make sure to reference this issue in the description. You can do so using [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests) as a reference.
